### ISSUE TITLE
Make a widget that can be used to list the ReviewTrusts that a person has

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#102]
This widget just needs to be demonstrated as a Story in Storybook. It doesn't need to be incorperated into the main app just yet.

The widget needs to look neat and tidy and be fit for human consuption.

Remember KISS. We just need to see the data. 

## what is review trust?

As users review each other's work we keep track of who does a good job of reviewing. If a person is usually right when they review simple-calc part 1 in js, then we might decide that we trust this person. If a person is trusted on a card then when they add a positive review, the card moves to the complete column. 

## Why display it?

People should aim to be trusted reviewers. If they have trust then it means they are doing a good job.  Trust is something worth earning so we want to show people where they are at. 

Also, the more trust we have in the people using Tilde, the better. If we can trust certain recruits then it means that staff members can do higher value tasks.

## The data 

The widget needs to be able to display data structures that looks something like this:

```
[
{
    content_item_title: "something",
    flavours: ["javascript","react"] 
}, 
{
    content_item_title: "something else",
    flavours: ["python","pytest"] 
}, 
]
```
The data structure might change a bit in the future, the APIs still need to be developed.

## looks

Here are some MaterialUI widgets that could be useful:

- Fixed Header table: https://material-ui.com/components/tables/#fixed-header (there can be one row per trust)
- Chip: https://material-ui.com/components/chips/#chip You can use chips to display the flavours

**Comment by babalwa-mbolekwa** [comment]
I am planning to make a PR by the 7th of June at 5pm.

**Comment by babalwa-mbolekwa** [comment]
I am planning to make a PR by the 14th of June. I couldn't make a PR by the 7th of June because of a blocker on setting up Tilde on my machine with Ubuntu and Docker. I am also planning on upskilling on Material UI.
Plans:

-  Upskill on Material UI
- Tilde repo setup on my machine [Done]
- Setup react storybook
- Create a story for the Review trusts widget.
- Push work to Tilde repo and make a PR by the 14th of June.

**Comment by sheenarbw** [comment]
Goal: draw a picture using storybook.

1. Run the storybook that is already built into Tilde. You dopnt need to reimplement it or anything. Just run npm run storybook and it will launch
2. Make a file at frontend/src/components/regions/UserDetails/ReviewTrustTable/Presentation.js. Make a react component in that file that just renders <div>Helloworld</div>
3. Make a story that draws your new component. Your story should be inside the folder frontend/src/stories
4. define the props for the component, pas in the sample data 
5. Upskill on material ui (just enough)
6. update the current component to draw the correct table
