### ISSUE TITLE
Create a widget that displays all the Teams that a user is in

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#103]

**Comment by babalwa-mbolekwa** [comment]
Goal: Create a widget and story that displays all teams that a user is in
Plan:
1. Create TeamsTable component inside frontend/src/components/regions/UserDetails/TeamsTable/Presentation.js
2. Create TeamsTable story inside frontend/src/stories/TeamsTable.stories.js
3. Make a PR by 30 June 2021 5pm.
