### ISSUE TITLE
If there is an open PR on a card, then display the age of that PR on the card. Eg 1 day ago, 2 days ago, etc

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#104]
We need to be able to see how long people are watiting for PRs to get dealt with

Requires:

- [x] #114 
- [x] #115

**Comment by babalwa-mbolekwa** [comment]
Goal: Display age of open PR on Agile Card if there is an open PR.
Plan:
1. Create a utils.js file in frontend/src/components/regions/AgileBoard/AgileCard/utils.js
2. Create a function inside utils.js that uses Github API, that will return PR age string if there is an Open PR.
3. Create a component that displays PR age and its story, 
4. Add PR age component to AgileCard component and story.
4. Make a PR by the 25th June at 5pm.

**Comment by babalwa-mbolekwa** [comment]
Updated plan:
1. Update user.json file in frontend/src/stories/fixtures/agileCard.json to use most recent data.
2. Create a Component in /frontend/src/components/widgets that will display age of Open PR
 - Create a function that will return difference between oldestOpenPrUpdatedTime and currentTIme.
3. Create a story for the component above.
4. Make a PR by the 25th of June at 5pm.
