### ISSUE TITLE
Implement a story for existing AgileCard widget

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#115]
The agile card widget exists at src/components/regions/AgileBoard/AgileCard/AgileCardActions/Presentation.js

Make sure you can get your story to draw a blue card.

In order to get the story right, you'll need to be able to understand what data gets passed to the widget. There are a few tricks here:

## React Dev tools

There are google chrome extensions that can help here. You can examine a component using chrome and see what props were passed in. So if you go to your board and examine a card you will see what props  it needs.

## look at what is inside your redux store

You can get a picture of all the stuff that the frontend knows by taking a look at what is stored in the redux store. You dont need to understand Redux to get this right, you would just need to know that redux exist and it contains data.

Navigate to your board and press F12, look at the console and see all the wild stuff that gets logged.  Expand the last thing that says "next state" and you'll se a biiiig object. If you click on Entities then youll see some cards and users there, and maybe some opther stuff.

When we render an AgileCard component then we pass it a card from `next_state.Entities.cards`

## Directory structure

If you make use of large data structures in your stories, then it's good to put them infiles inside src/stories/fixtures. Take a look at what is already in there.

You can make json or js files that contain the data you will need for this story

**Comment by babalwa-mbolekwa** [comment]
Goal: Implement a story for AgileCard widget
Plan:
1. Make a file at frontend/src/stories/AgileCardActions.stories.js
2. Upskill on using Google Chrome extensions (just enough) to examine component props
3. Upskill on Redux (just enough) to use Redux store
4. Create a story for AgileCard widget in AgileCardActions.stories.js file
5. Save all data structures to src/stories/fixtures
6. Make a PR by the 18th of June at 5pm
