### ISSUE TITLE
Upgrade the AgileCard story so that it shows cards in different situations

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#119]
We need to be able to see the card in different situations eg:

- review versus assigned (yellow versus blue)
- had a due time 
- has review emojis at the top 
- different statuses (these should display different buttons)
- pr count > 0 

Currently the cards are kinda ugly.Once we can get a complete story for a card we can work on making it look better

**Comment by babalwa-mbolekwa** [comment]
Goal: Upgrade AgileCard story to show different situations.
Plan: 
Show the following AgileCard instances on storybook:
1. Card of Reviewer vs Assigned (yellow vs blue)
2. Card with open pull requests
3. Card with Review emojies
4. Grayed out card vs Accessible card

6. Make a PR by 30 June 2021
