### ISSUE TITLE
Frontend bugfix: code reviews dont show up in the right order

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#125]
When looking at the details of a project, the competence reviews should be sorted according to timestamp, but they aren't. The latest review should be on top. 

Step 1: find an example of a card where the reviews are arriving in the wrong order. Get the data from the frontend by using the developer tools.

Step 2: update the story at CardDetailsModal.Reviews.stories so that it uses the data that you fetched. The bug should now be apparent when you view the story.

Step 3: update the relevent component so that it orders things corectly automatically. The latest review added will have the latest timestamp

**Comment by babalwa-mbolekwa** [comment]
Goal: Fix frontend bug - show code reviews in order starting from latest code review.
Plan: 
- Follow instructions steps
- Make a PR by the 15th of July 5pm.
