### ISSUE TITLE
Make Card Details modal responsive

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#126]
Some people do our bootcamp on their cellphones. This is currently a bit of a bad experience because when they open up the details of a card, they dont get presented with something responsive.

Take a look at CardDetailsModal.stories. Then update the presentation layout (and the layout of all sub components) so that the CardDetailsModal looks good on people's phones.

Check how materialui handles grids here https://material-ui.com/components/grid/

**Comment by babalwa-mbolekwa** [comment]
Goal: Make card details modal responsive.
Plan: 
1. Learn just enough about Material UI grids.
2. Update Presentation file for CardDetailsModal.
3. Make a PR by 16 July 2021 5pm.

**Comment by sheenarbw** [comment]
It turns out...it's not actually looking good on smaller devices.

This is important because some bootcampers do our bootcamp on their phone. We dont want to make those folk fail because they cant see what's happening. 

![Screenshot from 2021-09-10 07-24-45](https://user-images.githubusercontent.com/699166/132804154-42599bd5-94a2-47e2-ab67-52433bd6effd.png)

If you get the frontend running on your computer andopen up a details modal you'll see what I mean.
