### ISSUE TITLE
Board columns should fit the available page heightinstead of having a fixed height

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#156]
The Tilde board has columns that just end arbitrarily instead of extending to the bottom of the available space.

Take a look at how github handles drawing board columns. Zoom the browser in and out and see how the hight of the columns always makes sense. 

Please adjust the Tilde board so the columns work in the same way.

**Comment by babalwa-mbolekwa** [comment]
Goal: Make Board columns fit available page height.
Plan:
- Modify columns in frontend/src/components//AgileBoard/Presentation.js
- Make a PR by 27 August 2021, 5pm
