### ISSUE TITLE
Fix Bug: Users page and Card Summary page are not scrollable

### ISSUE THREAD

**Issue by babalwa-mbolekwa** [Umuzi-org/Tilde#193]
### Description:
- **Users Page:** When the content list exceeds the available height space, the rest of the content that overflows is hidden and the user cannot scroll upwards or downwards
- **Card Summary Page:** When the content list exceeds the available width and height space, the rest of the content that overflows is hidden and the user cannot scroll horizontally or vertically

### Expected behavior:
- A person viewing the Users Page should be able to scroll up and down when the list of Users overflow on the available height of the page
- A person viewing a team's Card Summary page should be able to scroll horizontally and vertically when the list of cards overflow

### Actual behavior:
![usersPageBug](https://user-images.githubusercontent.com/52567054/134481354-049ad5a9-506f-4ea8-8aca-a1ea38597ad2.png)

![cardSummaryPageBug](https://user-images.githubusercontent.com/52567054/134481415-e63f1af9-0f7a-462f-a9fc-07acee297600.png)

**Comment by sheenarbw** [comment]
Fixed
