### ISSUE TITLE
Bug: View access doesn't necessarily give people the ability to see a team

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#206]
I gave Andrew View access for C26. 

He navigated to the users page but the team didn't show up
I then gave him managment access to the team
He navigated to the users page and the team DID show up

This is probably something to do with the api endpoint that supplies the list of teams to be displayed. It is probably a backend problem.

These permissions were managed via a team - Andrew was in a team called "Partnerships" and the view and manage permissions were added to that team. Meaning Partnerships has access to C26.

Steps to fix:
0. Try to reproduce the error (will need the full stack to run in order to do so)
1. Write a test that exposes the problem
2. make the tests pass

**Comment by ry-oc** [comment]
@sheenarbw 

![image](https://user-images.githubusercontent.com/50435490/144560049-c64386d4-c3ac-45de-8c6c-37ce5b004a60.png)

Highlighted options are not present in the code, the incorrect permissions were given to Andrew  on the backend, see below:

![image](https://user-images.githubusercontent.com/50435490/144560197-adea7540-e17a-47ce-8920-8e061c54b9a8.png)
