### ISSUE TITLE
Align Tabs and Performance title to be centered with the container for mobile devices

### ISSUE THREAD

**Issue by Vuyisanani** [Umuzi-org/Tilde#261]
### Description:

Performance not centred, unlike Team membership title for mobile devices, We would like Performance to be centred as well as the anchor link Tabs

### Steps to reproduce:

1. Go to the dashboard Tab, on your mobile device
2. Compare performance title with Team membership title, performance is not centred
3. Please also align the Tabs to be centred with the page, as they are right-aligned

### Actual behavior:

<img width="344" alt="Screenshot 2021-11-24 at 02 34 58" src="https://user-images.githubusercontent.com/35369692/143150670-5273f83a-6b90-4b47-bf1d-730a603de13a.png">

### Client Setup Information

- Browser Version:
- Operating System:

**Comment by ry-oc** [comment]
Develop has been updated to fix this in another pr
