### ISSUE TITLE
When a user logs in with an Umuzi email address, prevent it from automatically creating a user

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#42]
This used to be an Umuzi-specific project, but this is no longer the case. Also auto-creating users for @umuzi logins has caused a few problems and confusions for users. Like "my board is empty because I logged in with a completely seperate email address". 

Currently: When a user logs in with their umuzi email address then a user is automatically created if it didn't exist. This is not the correct behavior. 

Do not automatically create any User instances when people log in. 

Please remove that functionality

**Comment by asradebe** [comment]
Claimed! Andy
