### ISSUE TITLE
run_automarker script should raise exception if automarker api not available

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#437]
The automarker is a standalone web application. 

Here is how you can access it through a management script.
```
python manage.py run_automarker "Person" ""
```

If the automarker web app is not running then `run_automarker` thinks that the learn'er's code is broken. This is bad.

Make use of the automarker health check endpoint to check if it's alive before actually attempting to review anything. 

To do this: go look at the automarker readme inside the main Tilde repo

**Comment by ry-oc** [comment]
Sheena did this cos she needed it
