### ISSUE TITLE
Write a script that can import dev_helpers/data/intro-to-tilde-course.json. Quickly please :)  

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#56]
In order to make developement easy, we want a quick and easy way to set up a little curriculum that demonstrates all the different card movements.

This syllabus already exists on our main instane, but loading up absolutely everything in the world into your local db is kinda a pain in the neck. 

Take a look at this: `curriculum_tracking/management/commands/export_curriculum.py`
This was used to create:
dev_helpers/data/intro-to-tilde-course.json

Make another script called `import curriculum` that takes the json and saves it into the db.

The sooner this is done, the sooner others can use it.

**Comment by ToyaSims** [comment]
Andy-Nkumane
