### ISSUE TITLE
Connect the backend to the develomment mongo database

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#69]
This issue requires #68 to be complete 

Make use of Djongo to connect to the mongodb database set up in issue #68 
https://nesdis.github.io/djongo/

Please note: Our default database is postgres and it needs to remain postgres. So when updating seettings.py please dont overwrite our wonderful postgres settings. This should help  you to set up multiple databases: https://docs.djangoproject.com/en/3.1/topics/db/multi-db/

**Comment by misterdabu** [comment]
I would like to work on this issue please assign it to me.
